// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTMMBot.Data;

namespace TTMMBot.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("TTMMBot.Data.Entities.Clan", b =>
            {
                b.Property<int>("ClanID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Tag")
                    .HasColumnType("TEXT");

                b.HasKey("ClanID");

                b.HasIndex("Tag", "Name")
                    .IsUnique();

                b.ToTable("Clan");
            });

            modelBuilder.Entity("TTMMBot.Data.Entities.Member", b =>
            {
                b.Property<int>("MemberID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("AllTimeHigh")
                    .HasColumnType("INTEGER");

                b.Property<int>("ClanID")
                    .HasColumnType("INTEGER");

                b.Property<int>("DiscordID")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<int>("SeasonHighest")
                    .HasColumnType("INTEGER");

                b.HasKey("MemberID");

                b.HasIndex("ClanID");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Member");
            });

            modelBuilder.Entity("TTMMBot.Data.Entities.Member", b =>
            {
                b.HasOne("TTMMBot.Data.Entities.Clan", "Clan")
                    .WithMany("Members")
                    .HasForeignKey("ClanID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
