version: '3.9'
services:
  mmbot.discord:
    build:
      context: .
      dockerfile: MMBot.Discord/Dockerfile
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Context=Host=postgres;Port=5432;Database=MMBotDB;Username=postgres;Password=P0stGresSQL2021
      - Discord__Token=*
    networks:
      - mmbot-network

  mmbot.blazor:
    build:
      context: .
      dockerfile: MMBot.Blazor/Server/Dockerfile
    ports:
      - "8081:443"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Context=Host=postgres;Port=5432;Database=MMBotDB;Username=postgres;Password=P0stGresSQL2021
      - ASPNETCORE_URLS=https://+;http://+ 
      - ASPNETCORE_HTTPS_PORT=8081 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=abc12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/Certificates/aspnetapp.pfx
      - Discord__AppSecret=*
      - Discord__AppId=*
    volumes:
      - ./MMBot.Blazor/Server/Certificates:/Certificates/
    networks:
      - mmbot-network

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P0stGresSQL2021
      POSTGRES_DB: MMBotDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mmbot-network

networks:
  mmbot-network:

volumes:
  postgres-data: