global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using System.Runtime.Serialization;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Logging;
global using MMBot.Data.Contracts;
global using MMBot.Data.Contracts.Entities;
global using MMBot.Data.Contracts.Enums;
global using MMBot.Data.Contracts.Helpers;
global using MMBot.Data.Helpers;
global using static MMBot.Data.Helpers.EFCoreHelpers;
