name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0.306
    
    - name: Install workload
      run: dotnet workload install wasm-tools

    - name: Build
      run: dotnet build MMBot.sln -c Release

    - name: Test
      run: dotnet test MMBot.sln --no-restore --verbosity normal

    - name: .NET Publish
      run: dotnet publish ./MMBot.Discord/MMBot.Discord.csproj -c Release -r linux-x64 --framework net7.0 /p:DebugType=None /p:DebugSymbols=false

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './MMBot.Discord/bin/Release/net7.0/linux-x64/publish/appsettings.json'
      env:
        DetailedErrors: false
        Discord.DevToken: ${{ secrets.DISCORD_DEV_TOKEN }}
        Discord.Token: ${{ secrets.DISCORD_TOKEN }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvc -i --delete-excluded --filter 'protect *.db' --filter 'protect *.log' --filter 'protect *.json'"
          SOURCE: MMBot.Discord/bin/Release/net7.0/linux-x64/publish/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          
    - name: .NET Publish
      run: dotnet publish ./MMBot.Blazor/Server/MMBot.Blazor.Server.csproj -c Release -r linux-x64 --framework net7.0 /p:DebugType=None /p:DebugSymbols=false

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './MMBot.Blazor/Server/bin/Release/net7.0/linux-x64/publish/appsettings.json'
      env:
        DetailedErrors: false
        Discord.AppId: ${{ secrets.DISCORD_APPID }}
        Discord.AppSecret: ${{ secrets.DISCORD_APPSECRET }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v3.4.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvc -i --delete-excluded --filter 'protect *.db' --filter 'protect *.log' --filter 'protect *.json'"
          SOURCE: MMBot.Blazor/Server/bin/Release/net7.0/linux-x64/publish/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET2 }}
          SCRIPT_AFTER: "sudo systemctl restart kestrel-mmblazor"
