name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: add discord.net feed
      run: dotnet nuget add source https://www.myget.org/F/discord-net/api/v3/index.json

    - name: Install dependencies2
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: .NET Publish
      run: dotnet publish ./MMBot.Discord/MMBot.Discord.csproj -c Release -r linux-x64 --no-self-contained /p:PublishReadyToRun=false /p:DebugType=None /p:DebugSymbols=false

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './MMBot.Discord/bin/Release/net6.0/linux-x64/publish/appsettings.json'
      env:
        DetailedErrors: false
        Discord.DevToken: ${{ secrets.DISCORD_DEV_TOKEN }}
        Discord.Token: ${{ secrets.DISCORD_TOKEN }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete-excluded --filter 'protect *.db' --filter 'protect *.log' --filter 'protect *.json'"
          SOURCE: MMBot.Discord/bin/Release/net6.0/linux-x64/publish/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          
    - name: .NET Publish
      run: dotnet publish ./MMBot.Blazor/Server/MMBot.Blazor.Server.csproj -c Release -r linux-x64 --self-contained /p:PublishReadyToRun=false /p:DebugType=None /p:DebugSymbols=false

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './MMBot.Blazor/Server/bin/Release/net6.0/linux-x64/publish/appsettings.json'
      env:
        DetailedErrors: false
        Discord.AppId: ${{ secrets.DISCORD_APPID }}
        Discord.AppSecret: ${{ secrets.DISCORD_APPSECRET }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete-excluded --filter 'protect *.db' --filter 'protect *.log' --filter 'protect *.json'"
          SOURCE: MMBot.Blazor/Server/bin/Release/net6.0/linux-x64/publish/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET2 }}
